version: '3.8'

services:
  coopcredit-frontend:
    build: .
    container_name: coopcredit-frontend
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - coopcredit-network

networks:
  coopcredit-network:
    driver: bridge
